apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweets
  template:
    metadata:
      labels:
        app: tweets
    spec:
      containers:
      - name: tweets
        image: chaim022/tweets:7
        ports:
        - containerPort: 8000
        env:

        - name: MONGODB_USER
          value: IRGC
        - name: MONGODB_PASSWORD
          value: iraniraniran
        - name: MONGODB_DATABASE
          value: IranMalDB
        - name: MONGO_COLLECTION
          value: tweets


---
apiVersion: v1
kind: Service
metadata:
  name: tweets
spec:
  selector:
    app: tweets
  ports:
  - port: 8000
    targetPort: 8000
